packages:
  - internals/website-examples
  - packages/*
  - test
  - website
catalogs:
  agentica:
    "@agentica/core": ^0.30.3
    "@agentica/rpc": ^0.30.3
  samchon:
    "@nestia/benchmark": ^7.1.1
    "@nestia/core": ^7.1.1
    "@nestia/e2e": ^7.1.1
    "@nestia/editor": ^7.1.1
    "@nestia/fetcher": ^7.1.1
    "@nestia/migrate": ^7.1.1
    "@nestia/sdk": ^7.1.1
    "@samchon/openapi": ^4.5.0
    embed-prisma: ^1.1.0
    embed-typescript: ^1.0.1
    prisma-markdown: ^3.0.0
    tgrid: ^1.2.0
    tstl: ^3.0.0
    typia: ^9.5.0
  typescript:
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.8.3
  libs:
    openai: ^5.2.0

useNodeVersion: 22.15.0