packages:
  - internals/*
  - packages/*
  - test
  - website
catalogs:
  agentica:
    "@agentica/core": ^0.29.0
    "@agentica/rpc": ^0.29.0
  samchon:
    "@nestia/benchmark": ^7.0.0
    "@nestia/core": ^7.0.0
    "@nestia/e2e": ^7.0.0
    "@nestia/fetcher": ^7.0.0
    "@nestia/migrate": ^7.0.0
    "@nestia/sdk": ^7.0.0
    "@samchon/openapi": ^4.3.3
    embed-prisma: ^1.1.0
    embed-typescript: ^1.0.1
    prisma-markdown: ^3.0.0
    tgrid: ^1.1.0
    tstl: ^3.0.0
    typia: ^9.3.1
  typescript:
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.8.3
  libs:
    openai: ^5.2.0

useNodeVersion: 22.15.0